In [1]:
import numpy as np

In [21]:
c = 5
x = np.arange(1, 4).T
y = np.arange(3, 7)
z = np.arange(4, 7).T
A = np.array([[1, 2, 0],
              [0, 2, 3],
              [4, 6, 1],
              [0, 0, 1]])
B = np.array([[1, 0],
              [0, 1],
              [1, 1]])

In [6]:
result = 0
for x_i in x:
    result += x_i
print(result)
    
print(np.sum(x))

6
6


In [7]:
result = 1
for x_i in x:
    result *= x_i
print(result)

print(np.prod(x))

6
6


In [10]:
np.sum(np.exp(np.log(x)))

6.0

In [11]:
np.sum(5*x)

30

In [12]:
np.sum(c*x)

30

In [13]:
c * np.sum(x)

30

In [14]:
np.sum(x + z)

21

In [15]:
np.sum(x) + np.sum(z)

21

In [16]:
np.sqrt(np.sum(x ** 2))

3.7416573867739413

In [17]:
np.linalg.norm(x)

3.7416573867739413

In [22]:
np.dot(A, x)

array([ 5, 13, 19,  3])

In [31]:
result = np.zeros(A.shape[0])
for i in range(4):
    r = 0
    for j in range(3):
        r += A[i, j] * x[j]
    result[i] = r

print(result)

[  5.  13.  19.   3.]


In [25]:
np.dot(y, A)

array([23, 44, 23])

In [26]:
np.dot(np.dot(y, A), x)

180

In [27]:
np.dot(np.dot(x.T, A.T), y.T)

180

In [28]:
np.dot(A, B)

array([[1, 2],
       [3, 5],
       [5, 7],
       [1, 1]])

In [29]:
np.dot(B.T, A.T)

array([[1, 3, 5, 1],
       [2, 5, 7, 1]])

In [30]:
np.dot(A, B).T

array([[1, 3, 5, 1],
       [2, 5, 7, 1]])

In [32]:
result = np.zeros((A.shape[0], B.shape[1]))
for i in range(4):
    for k in range(2):
        r = 0
        for j in range(3):
            r += A[i, j] * B[j, k]
        result[i, k] = r
print(result)

[[ 1.  2.]
 [ 3.  5.]
 [ 5.  7.]
 [ 1.  1.]]


In [34]:
result = np.zeros(A.shape[0])
for i in range(4):
    result[i] = sum(A[i, :])
    
print(result)

[  3.   5.  11.   1.]


In [35]:
result = np.zeros(A.shape[1])
for j in range(3):
    result[j] = sum(A[:, j])
    
print(result)

[  5.  10.   5.]


In [37]:
def fac(n):
    return 1 if n == 0 else n * fac(n-1)

fac(5)

120

In [38]:
def fac_prod(n):
    return np.prod(np.arange(n, 0, -1))

fac(5)

120

In [40]:
f = lambda x: np.sin(c * x ** 2)

np.sum(f(y))

-1.5601782243117437